require 'huginn_agent'

#HuginnAgent.load 'huginn_steam_check_server_per_ip_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_steam_check_server_per_ip_agent/steam_check_server_per_ip_agent'
